### ISSUE TITLE
ERROR: Privacy.MediaDrm.getProperty.ByteArray

### ISSUE THREAD

**Issue by Anderhar** [0bbedCode/XPL-EX#11]
The error pop-up occurs if any app attempts to read DRM ID with the "Read identifiers" option enabled, whereas DRM ID is still not spoofed and exposes as it is. 

As a long-time XPrivacyLua user, I valued it for its ability to spoof DRM ID (to AAAA[...]AAAA= by default), so with XPL-EX something has changed here.

Tested on official `ArrowOS 13.1` with `MicroG`, `Magisk 27.0` and `LSPosed_mod 1.9.3`, using [DevCheck](https://play.google.com/store/apps/details?id=flar2.devcheck) and [TrustDevice](https://github.com/trustdecision/trustdevice-android).

[LOGCAT.TXT](https://github.com/0bbedCode/XPL-EX/files/15287822/LOGCAT.TXT)

**Comment by 0bbedCode** [comment]
Privacy is part of the Old Collection the Final Release for this Specific XPLEX Version will be out soon and Auto Disable Privacy Hooks for now use the PrivacyEx hooks and Keep Disabled the Privacy Hooks as I will no longer assist any errors that happen in the Privacy Collection. Issues will only be helped for the PrivacyEx collection and any other managed by me ObbedCode not M66B.

**Comment by Anderhar** [comment]
> Privacy is part of the Old Collection the Final Release for this Specific XPLEX Version will be out soon and Auto Disable Privacy Hooks for now use the PrivacyEx hooks and Keep Disabled the Privacy Hooks as I will no longer assist any errors that happen in the Privacy Collection. Issues will only be helped for the PrivacyEx collection and any other managed by me ObbedCode not M66B.

A similar error `PrivacyEX.MediaDrm.getProperty.ByteArray` may occur when your `ID Unique` hook is used with some incorrect DRM ID value entered in Settings Values. 

Unfortunately, by default DRM spoofing does not provided at all unless set manually by the user in Settings Values. It would be nice if all users would always get some uniform DRM ID value when `ID Unique` is checked (as it was in XPrivacyLua).

I assume the `AAAA[...]AAAA=` result is achieved in DevCheck when DRM ID is filled with zeros, but I don't know exactly how many zeros are needed to match XPrivacyLua. The source code will tell you, I think.

Anyway, please deal with this DRM ID, because it's one of the nastiest fingerprinting vectors. And thank you for everything else, of course.

**Comment by 0bbedCode** [comment]
> > Privacy is part of the Old Collection the Final Release for this Specific XPLEX Version will be out soon and Auto Disable Privacy Hooks for now use the PrivacyEx hooks and Keep Disabled the Privacy Hooks as I will no longer assist any errors that happen in the Privacy Collection. Issues will only be helped for the PrivacyEx collection and any other managed by me ObbedCode not M66B.
> 
> A similar error `PrivacyEX.MediaDrm.getProperty.ByteArray` may occur when your `ID Unique` hook is used with some incorrect DRM ID value entered in Settings Values.
> 
> Unfortunately, by default DRM spoofing does not provided at all unless set manually by the user in Settings Values. It would be nice if all users would always get some uniform DRM ID value when `ID Unique` is checked (as it was in XPrivacyLua).
> 
> I assume the `AAAA[...]AAAA=` result is achieved in DevCheck when DRM ID is filled with zeros, but I don't know exactly how many zeros are needed to match XPrivacyLua. The source code will tell you, I think.
> 
> Anyway, please deal with this DRM ID, because it's one of the nastiest fingerprinting vectors. And thank you for everything else, of course.

Just randomize it then there you go you got the format , DRM has a randomizer do note the randomize value will not be the output for application as they read it differently but still being spoofed to the value you set (wont get deep into it understand its programmer stuff). I polished the Randomizer to always work best and the Hook can you show me where when its not working. What Hooks you selected (a whole list of hook groups) what Update, Can you clear XPLEX App data (your stuff wont be lost).
I dont have anyone else besides you with this issue Im very very very confused.
