### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Neebly** [0bbedCode/XPL-EX#6]
Please, submit your fantastic app to F-Droid repositories:
https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/

**Comment by 0bbedCode** [comment]
Will work on this when I have time I also need to check XDA , I am very busy at times not always but at times. Will do this !

**Comment by ThreeDeeJay** [comment]
Is the source code ready to compile?
Perhaps @IzzySoft can help putting it up on his repository 🤔

**Comment by IzzySoft** [comment]
Seems to be a fork of XPrivacyLua (as the repo properly reflects, thanks for keeping the connection!), and still uses its packageName (`eu.faircode.xlua`) which is an issue – unless Marcel transferred ownership to you. If that happened, can you please point it out? If not, a different package name would be needed (e.g. `0bbedCode.xplex`). Then it can be added to IzzyOnDroid, scanner results look fine!

**Comment by 0bbedCode** [comment]
> Seems to be a fork of XPrivacyLua (as the repo properly reflects, thanks for keeping the connection!), and still uses its packageName (`eu.faircode.xlua`) which is an issue – unless Marcel transferred ownership to you. If that happened, can you please point it out? If not, a different package name would be needed (e.g. `0bbedCode.xplex`). Then it can be added to IzzyOnDroid, scanner results look fine!

will this be an issue to F-Droid since I dont own it ?

**Comment by ThreeDeeJay** [comment]
If that's gonna be a problem, I'd be okay with just adding a GitHub actions CI workflow to get automated APK builds from GitHub releases using Obtainium to make it easier for everyone 👌

**Comment by IzzySoft** [comment]
> will this be an issue to F-Droid since I dont own it ?

Yes. Especially as there already is an app using this packageName, so there'd be a conflict. Basically, keeping the packageName means you're pretending to be the legal successor – but this is a different app, so it should have its own packageName.

**Comment by ThreeDeeJay** [comment]
@0bbedCode @IzzySoft I tried setting up a [GitHub actions workflow](https://github.com/ThreeDeeJay/XPL-EX/blob/new/.github/workflows/build.yml#L28-L38) but I'm getting some [compilation errors](https://github.com/ThreeDeeJay/XPL-EX/actions/runs/9782417579/job/27008669881#step:6:2720). 
This usually works with other apps, but perhaps I'm missing something.🤔 
Do you guys have a way to compile the APK programmatically via the command line so I can try to port it to the CI? 
Also the main XPL-EX repo would probably need to add the signing keys to secrets so they're called privately and we can keep the same APK signature across builds to be able to update without having to uninstall the old version first.
That is, at least while the F-Droid situation gets sorted out 👌

**Comment by ThreeDeeJay** [comment]
Found a fork that figured out how to build the APK https://github.com/Fearlein/XPL-EX-CANARY/actions/runs/9436761981
So I guess now we just need to figure out how to make it use @0bbedCode's signing keys instead of [whatever's going on here](https://github.com/Fearlein/XPL-EX-CANARY/actions/runs/9436761981/workflow#L62) and make it push new APKs for each update to GitHub releases, so then we can just use something like [Obtainium](https://github.com/ImranR98/Obtainium) to get updates.

**Comment by IzzySoft** [comment]
Sorry, I can't help with that: I'm no Android dev, and also not familiar with the CI here…
