### ISSUE TITLE
Migration xlua.db from XPL to XPL-EX

### ISSUE THREAD

**Issue by eku** [0bbedCode/XPL-EX#7]
The migration from XPrivacy Lua to XPL-EX does not work.

I saved the files under `/data/system/xlua` and restored them after moving to XPL-EX, but it is ignored.

```
P2T:/data/system/xlua # ls -l
total 2520
-rwxrwxrwt 1 system system 2580480 2024-04-28 13:03 xlua.db
-rwxrwxrwt 1 system system       0 2024-04-28 13:03 xlua.db-journal
```

**Comment by 0bbedCode** [comment]
It is not ignored in certain cases the OLD files can not be deleted for whatever reason I tried CHOWN + CHMOD and many other ways but the old files wont budge so for now manually delete the old files, it wont use it. It will create a new directory "/data/system/xplex-xxx". (Make sure that directory exist if so delete the old one)

**Comment by eku** [comment]
I don't understand what you're trying to tell me. 

The configuration after the installation of XPL-XE is empty, so settings from XPL are not migrated to the new location.

**Comment by 0bbedCode** [comment]
> I don't understand what you're trying to tell me.
> 
> The configuration after the installation of XPL-XE is empty, so settings from XPL are not migrated to the new location.

What im saying is, I for some reason SOMETIMES FOR SOME USERS, cannot modify the old folder, so if this happens in the "/data/system/" create the folder if it dosnt exist "xplex-xxx" xxx being random letters, then find the old "xlua" folder copy everything in there paste it into the new "xplex-" folder, then delete the "xplex" folder again this will be all in the "/data/system/" folder.
